name: radio_tropical
description: Aplicativo de Rádio Tropical com notificações

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.35
  audio_service: ^0.18.9
  just_audio_background: ^0.0.1+16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/radio_icon.png