name: minha_radio_app
description: "Um aplicativo de rádio simples com reprodução em segundo plano."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Adapte para a sua versão do SDK do Flutter se necessário

dependencies:
  flutter:
    sdk: flutter

  # Pacote principal para gerenciar áudio em segundo plano e notificações
  audio_service: ^0.18.12

  # Player de áudio que vai tocar a rádio
  just_audio: ^0.9.36

  # Gerencia o foco de áudio (ex: pausa quando recebe uma ligação)
  audio_session: ^0.1.18

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

